[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "financial-data-platform"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "httpx",
    "minio",
    "psycopg[binary]",
	"dbt-core",
	"dbt-postgres",
	"bs4"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "mypy"

]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
financial_data = ["py.typed"]

[tool.mypy]
python_version = "3.12"
mypy_path = "src"
files = ["src"]
explicit_package_bases = true
check_untyped_defs = true
